[project]
name = "scholar-haozhou-wang"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ipykernel>=6.29.5",
    "scholarly>=1.7.11",
]
