[project]
name = "scholar-haozhou-wang"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "google-search-results>=2.4.2",
    "ipykernel>=6.29.5",
]
