name: Update 3DGS Sheet Data

on:
  schedule:
    - cron: '0 0 * * 1'  # 每周一UTC午夜运行
    # - cron: '*/3 * * * *'  # 每3分钟运行一次（测试用）
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
        cache-dependency-glob: |
          **/pyproject.toml
    - name: Install dependencies with uv
      run: cd py/ && uv sync

    - name: Fetch public sheet data
      run: cd py/ && uv run get_google_scholar.py

    - name: Commit changes if updated
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add files/scholar.json
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Auto-update google scholar data"
          git push
        fi
